### ISSUE TITLE
Einbettung ins Wiki?

### ISSUE THREAD

**Issue by laim93** [AUSoftAndreas/students#4]
Was ist ein Netzteil?
Zu aller erst muss man sagen das, dass Netzteil quasi das Herz eines Computer ist. Den die Aufgabe eines Netzteils ist es euren Computer bzw. die einzelnen Komponenten mit Strom zu versorgen.
Hierfür muss man wissen, dass der Strom aus der Steckdose sogenannter Gleichstrom ist. Der Computer benötigt allerdings sogenannten Wechselstrom.

Das bedeutet:
Das Netzteil ist ein "Transformator" welcher den Gleichstrom aus der Steckdose in den für die Komponenten benötigten Wechselstrom umwandelt.

Wie funktioniert ein Netzteil?
Schaut man sich den Aufbau eines Netzteils an, stellt man fest, dass es viele verschiedene Anschlüsse hat. Der Grund dafür ist das fast jedes Bauteil eines Computers über das Netzteil seinen Strom bezieht. Jedoch benötigt nicht jedes Bauteil gleich viel Strom und nicht die gleiche Spannung. Deshalb passt das Netzteil für jedes einzelne Kabel die Stromstärke und die Spannung vorher an.
Ein Beispiel hierfür ist, würde der ATX-Stecker in den CPU-Stromsteckplatz passen, könnte es passieren, dass der Prozessor kaputt geht, weil er einer zu hohen Stromstärke/Spannung ausgesetzt wäre.
Dies ist mit ein Grund warum es verschiedene Stecker gibt, damit solche Fehler im Vorfeld vermieden werden können.

Des weiteren unterscheidet man zwischen modularen und non-modularen Netzteilen.
Hierbei ist der unterschied recht simple, bei modularen Netzteilen kann man überflüssige Kabel abnehmen. Dies führt zu einer saubereren Verkabelung und gewährleistet mehr Übersicht und eine bessere Kühlung des Systems.
Bei non-modularen Netzteilen hingegen sind alle Kabel fest verlötet und somit nicht abnehmbar.

80 PLUS ist eine im Jahr 2004 gegründete Initiative, welche Netzteile auf ihre Effizienz testet. Hierbei zeichnet die Initiative Netzteil aus, welche im Test eine Effizient von über 80 Prozent leisten und sich damit als Stromsparend erweisen.
Je nach Effizienz verwendet die Initiative die Zusatz Zertifikate: Bronze, Silver, Gold, Platinum und Titanium.                                                                                                           

 

Was ist Effizienz?

Die Effizienz ist eine Prozentwert, welcher angibt, wie viel des verbrauchten Stroms tatsächlich dem Computer zur Verfügung steht. Das heißt, dass ein Netzteil mit höherer Effizienz stromsparender ist, als ein Netzteil mit niedriger Effizienz. 

Eine Beispiel Rechnung:

Ein Netzteil hat eine Effizienz von 80 Prozent und versorgt einen PC, welcher derzeit 300 Watt benötigt. Deshalb rechnet man 300/80*100 = 375. Der tatsächliche Stromverbrauch in dieser Situation liegt also bei 375 Watt.
Hätte das Netzteil eine Effizienz von 90 Prozent würde man rechnen 300/90*100 = 333. Damit liegt der tatsächliche Stromverbrauch hierbei bei ca. 333 Watt.
Anhand des Beispiels kann man erkennen das, dass Effizientere Netzteil auch stromsparender ist.

 

Anhand der folgenden Tabelle kann man nachvollziehen wie Effizient ein Netzteil sein muss um eine entsprechende Zertifizierung zu bekommen.

[Effizienz Tabelle](http://www.netzteil-test.de/wp-content/uploads/2015/11/tabelle-80-plus.jpg)

**Comment by AUSoftAndreas** [comment]
ist eingebaut
